name: Appimage
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ "test" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    container: artixlinux/artixlinux:latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      if: always()
      run: |
        sed -i 's/DownloadUser/#DownloadUser/g' /etc/pacman.conf
        pacman -Syu --noconfirm base-devel strace patchelf curl wget \
          desktop-file-utils git artix-archlinux-support llvm mesa xorg-server-xvfb \
          vulkan-radeon vulkan-intel vulkan-nouveau pulseaudio pulseaudio-alsa pipewire 
        pacman-key --init && pacman-key --populate archlinux
        printf "\n[extra]\nInclude = /etc/pacman.d/mirrorlist-arch\n" | tee -a /etc/pacman.conf
        sudo pacman -Syu --noconfirm \
          zsync \
          catch2 \
          enet \
          gamemode \
          cmake \
          gcc13 \
          glslang \
          glu \
          hidapi \
          xcb-util-wm \
          xcb-util-image \
          xcb-util-renderutil \
          libxkbcommon-x11 \
          libxi \
          nasm \
          qt5-base \
          qt5-tools \
          qt5-webengine \
          qt5-multimedia \
          qt5-wayland \
          mbedtls2 \
          fmt \
          nlohmann-json \
          aom \
          libass \
          haskell-gnutls \
          sdl2 \
          libva \
          meson \
          ninja \
          x264 \
          x265 \
          numactl \
          libvpx \
          libfdk-aac \
          libopusenc \
          ffmpeg \
          svt-av1 \
          dav1d \
          boost \
          clang \
          vulkan-headers \
          ffmpeg4.4 \
          zip \
          unzip \
          boost-libs \
          qt5ct
   
    - name: Install debloated llvm-libs
      run: |
        LLVM="https://github.com/pkgforge-dev/llvm-libs-debloated/releases/download/continuous/llvm-libs-nano-x86_64.pkg.tar.zst"
        wget "$LLVM" -O ./llvm-libs.pkg.tar.zst
        pacman -U --noconfirm ./llvm-libs.pkg.tar.zst

    - name: Compile Torzu Optimized
      run: |
        chmod +x ./*-appimage.sh && ./*-appimage.sh v3
        mkdir -p dist
        mv *.AppImage* dist/

    - name: Check version file
      run: |
       cat ~/version
       echo "APP_VERSION=$(cat ~/version)" >> "${GITHUB_ENV}"
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4.6.1
      with:
        name: AppImage
        path: 'dist'
        
    - name: Upload version file
      uses: actions/upload-artifact@v4.6.1
      with:
       name: version
       path: ~/version
    
  release:
      name: "release"
      if: ${{ github.ref_name == 'test' }}
      needs: [build]
      permissions: write-all
      runs-on: ubuntu-latest

      steps:
        - uses: actions/download-artifact@v4.1.9
          with:
            name: AppImage
        - uses: actions/download-artifact@v4.1.9
          with:
            name: version

        - name: Read version
          run: |
            cat version
            export VERSION="$(<version)"
            echo "APP_VERSION=${VERSION}" >> "${GITHUB_ENV}"
    
        #Version Release
        - name: Continuous Releaser
          uses: softprops/action-gh-release@v2
          with:
            name: "Torzu AppImage for Steamdeck: ${{ env.APP_VERSION }}"
            tag_name: "${{ env.APP_VERSION }}"
            prerelease: false
            draft: false
            generate_release_notes: false
            make_latest: true
            files: |
              *.AppImage*
          continue-on-error: false
