name: Build Torzu
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  torzu_build:
    name: Torzu AppImage
    runs-on: ubuntu-latest
    container: ghcr.io/pkgforge-dev/archlinux:latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      if: always()
      run: |
        sed -i 's/DownloadUser/#DownloadUser/g' /etc/pacman.conf
        pacman -Syu --noconfirm base-devel strace patchelf curl wget \
          desktop-file-utils git llvm mesa xorg-server-xvfb \
          vulkan-radeon vulkan-intel vulkan-nouveau pulseaudio pulseaudio-alsa pipewire 
        pacman-key --init && pacman-key --populate archlinux
        sudo pacman -Syu --noconfirm \
          zsync \
          catch2 \
          enet \
          gamemode \
          cmake \
          gcc \
          gcc-libs \
          glslang \
          glu \
          hidapi \
          xcb-util-wm \
          xcb-util-image \
          xcb-util-renderutil \
          libxkbcommon-x11 \
          libxi \
          nasm \
          qt5-base \
          qt5-tools \
          qt5-webengine \
          qt5-multimedia \
          qt5-wayland \
          qt6-base \
          qt6-multimedia \
          qt6-wayland \
          qt6-tools \
          qt6ct \
          gst-plugins-base \
          gst-plugins-good \
          gst-plugins-bad \
          gst-plugins-ugly \
          mbedtls2 \
          fmt \
          nlohmann-json \
          aom \
          libass \
          haskell-gnutls \
          sdl2 \
          libva \
          meson \
          ninja \
          x264 \
          x265 \
          numactl \
          libvpx \
          libfdk-aac \
          libopusenc \
          ffmpeg \
          svt-av1 \
          dav1d \
          boost \
          clang \
          vulkan-headers \
          ffmpeg4.4 \
          zip \
          unzip \
          boost-libs \
          qt5ct
   
    - name: Install debloated dependencies
      run: |
        chmod +x ./get-dependencies.sh && ./get-dependencies.sh

    - name: Compile Torzu Optimized
      run: |
        chmod +x ./torzu-appimage.sh && ./torzu-appimage.sh
        mkdir -p dist
        mv *.AppImage* dist/

    - name: Check version file
      run: |
       cat ~/version
       echo "APP_VERSION=$(cat ~/version)" >> "${GITHUB_ENV}"
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4.6.1
      with:
        name: AppImage
        path: 'dist'
        
    - name: Upload version file
      uses: actions/upload-artifact@v4.6.1
      with:
       name: version
       path: ~/version
       
  android: 
    runs-on: ubuntu-latest
    name: "Torzu nightly (android)"
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install ccache apksigner glslang-tools libvulkan-dev -y
          
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false
        
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        
      - name: Accept Android SDK Licenses
        run:  |
          yes | sdkmanager --licenses
          sdkmanager "ndk;26.3.11579264" "cmake;3.22.1"

      - name: Compile Torzu android
        run: |
          chmod +x ./torzu-android.sh
          ./torzu-android.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4.6.1
        with:
          name: android-universal
          path: torzu/src/android/artifacts/
          
  release:
      name: "release"
      if: ${{ github.ref_name == 'main' }}
      needs: [torzu_build, android]
      permissions: write-all
      runs-on: ubuntu-latest

      steps:
        - uses: actions/download-artifact@v4.1.9
          with:
            name: AppImage
            
        - uses: actions/download-artifact@v4.1.9
        
          with:
            name: android-universal
            
        - uses: actions/download-artifact@v4.1.9
          with:
            name: version

        - name: Read version
          run: |
            cat version
            export VERSION="$(<version)"
            echo "APP_VERSION=${VERSION}" >> "${GITHUB_ENV}"
            echo "date=$(date +'%Y-%m-%d')" >> "$GITHUB_ENV"
            
        - name: Delete same tag release
          run: |
            gh release delete "Torzu-${{ env.date }}-${{ env.APP_VERSION }}" --repo "${GITHUB_REPOSITORY}" --cleanup-tag  -y
            sleep 5
          env:
            GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          continue-on-error: true               

        - name: Nightly Releaser
          uses: softprops/action-gh-release@v2
          with:
            name: "Torzu Nightly: ${{ env.APP_VERSION }}"
            tag_name: "Torzu-${{ env.date }}-${{ env.APP_VERSION }}"
            prerelease: false
            draft: false
            generate_release_notes: false
            make_latest: true
            files: |
              *.AppImage*, *.apk
          continue-on-error: false
